apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xchildpausables.example.io
spec:
  group: example.io
  names:
    kind: XChildPausable
    plural: xchildpausables
  claimNames:
    kind: ChildPausable
    plural: childpausables
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  value:
                    type: string
                  config:
                    type: object
                    additionalProperties: true
                required:
                - value
            required:
            - parameters
          status:
            type: object
            properties:
              conditions:
                type: array
                items:
                  type: object
              currentHash:
                type: string
              previousHash:
                type: string
                default: initialValue

