apiVersion: example.io/v1alpha1
kind: Pausable
metadata:
  name: dev-pausable
  namespace: default
spec:
  parameters:
    value: "development-value"
    config:
      environment: "development1223weqwqwsafsdsdf2"
      region: "us-west-2"
      debug: "true"

